"<!doctype html>\r\n"
"<html>\r\n"
"<body>\r\n"
"\r\n"
"<!-- Info page -->\r\n"
"<!-- POST info=?-->\r\n"
"<!-- Request info&date&time&temp&mqtt&AutoModeCurrent&on&off&Status&power&IP&pwd&signal& -->\r\n"
"\r\n"
"\r\n"
"\r\n"
"<style>\r\n"
"table { width:50%;\r\n"
"        margin-left:auto;\r\n"
"        margin-right:auto;		\r\n"
"}\r\n"
"\r\n"
"th,td {display: none;\r\n"
"       border-radius: 8px;\r\n"
"	   font-size:32px;\r\n"
"}\r\n"
"\r\n"
"th {background-color: rgba(128, 128, 128, 0.48);\r\n"
"    margin:5px;	\r\n"
"}\r\n"
"\r\n"
"td {text-align:center;\r\n"
"}\r\n"
"\r\n"
"a {text-decoration:none;\r\n"
"   color:black;\r\n"
"   display:block;\r\n"
"   width:100%;\r\n"
"}\r\n"
"\r\n"
"#myProgress{\r\n"
"  width: 100%;\r\n"
"  background-color:gray;\r\n"
"   border-radius: 4px;\r\n"
"}\r\n"
"#myBar{\r\n"
" width:0;\r\n"
" height:20px;\r\n"
" background-color:green;\r\n"
" text-align: center;\r\n"
" line-height: 20px;\r\n"
" color: white;\r\n"
" border-radius: 4px;\r\n"
" font-size: 16px;\r\n"
"}\r\n"
"</style>\r\n"
"\r\n"
"<script type='text/javascript'>\r\n"
"\r\n"
"window.onload=function(){\r\n"
"//Post request info ...\r\n"
"request('/info=?');\r\n"
"}\r\n"
"function byId(id){return document.getElementById(id)};\r\n"
"function byClass(id){return document.getElementsByClassName(id)[0]};\r\n"
"function byClassi(id,i){return document.getElementsByClassName(id)[i]};\r\n"
"function byTag(id){return document.getElementsByTagName(id)[0]};\r\n"
"var urladdress=window.location;\r\n"
"\r\n"
"function espInfo(info){\r\n"
"<!-- Request info&date&time&temp&mqtt&on&off&Status&power&IP&ssid&pwd&signal& -->\r\n"
"\r\n"
"   var info=info.split('&');\r\n"
"   console.log(info);\r\n"
"   if(info.length>0){\r\n"
"      for(i=1;i<info.length;i++){\r\n"
"	    switch(i){\r\n"
"		case 1:\r\n"
"		 console.log(info[i]);\r\n"
"		 byId('hl1').innerHTML=info[i];\r\n"
"		 byId('hl1').style.display='block';\r\n"
"		 break;\r\n"
"		case 2:\r\n"
"		 byId('hl2').innerHTML =\"Temperature: \"+info[i];\r\n"
"		 byId('hl2').style.display='block';\r\n"
"		 break;\r\n"
"		case 3:\r\n"
"		 byId('hl2').innerHTML =byId('hl2').innerHTML+ \"<br>\"+\"MQTT:\"+info[i];\r\n"
"		 byId('hl2').style.display='block';\r\n"
"		 break;\r\n"
"		case 4:\r\n"
"		   byId('hl3').innerHTML=info[i] + \"<br>\";\r\n"
"		  //byId('hl3').innerHTML=byId('hl3').innerHTML + number+\"<br>\";\r\n"
"		 break;\r\n"
"		case 5:\r\n"
"		 var period=info[i];\r\n"
"		 var hour=parseInt(period/60);\r\n"
"		 var minute=period - 60*hour;\r\n"
"		 if (hour < 10) hour=\"0\"+hour;\r\n"
"		 if (minute <10) minute= \"0\" + minute;		\r\n"
"		 byId('hl3').innerHTML = byId('hl3').innerHTML+\"On \"+hour+\":\"+minute+ \"<br>\";\r\n"
"		 byId('hl3').style.display='block';\r\n"
"		 break;\r\n"
"		case 6:\r\n"
"		 var period=info[i];\r\n"
"		 var hour=parseInt(period/60);\r\n"
"		 var minute=period-60*hour;\r\n"
"		 if (minute <10) minute= \"0\" + minute;\r\n"
"		 if (hour < 10) hour=\"0\"+hour;\r\n"
"		 byId('hl3').innerHTML = byId('hl3').innerHTML + \"Off \" + hour+ \":\" + minute;\r\n"
"		 byId('hl3').style.display='block';\r\n"
"		 break;\r\n"
"		case 7:\r\n"
"		  switch(info[i]){\r\n"
"		   case '0':\r\n"
"		    var mode=\"MANUAL\";\r\n"
"		   break\r\n"
"		   case '1':\r\n"
"		    var mode=\"SLEEP\";\r\n"
"		   break;\r\n"
"		   case '2':\r\n"
"		    var mode=\"AUTO\";\r\n"
"		   break;\r\n"
"		  }\r\n"
"		 byId('hl4').innerHTML = \"MODE <br>\"+mode;\r\n"
"		 byId('hl4').style.display='block';\r\n"
"		 break;\r\n"
"		case 8:\r\n"
"		  if(info[i]==1) pwr=\"ON\";\r\n"
"		   else pwr=\"OFF\";\r\n"
"		  byId('hl5').innerHTML = \"POWER <br> \"+pwr;\r\n"
"		  byId('hl5').style.display='block';\r\n"
"		  break;\r\n"
"		case 9:\r\n"
"		  byId('hl6').innerHTML = \"IP <br> \" +info[i];\r\n"
"		  byId('hl6').style.display='block';\r\n"
"		  break; \r\n"
"		case 10:\r\n"
"		  byId('hl7').innerHTML = \"SSID <br> \"+info[i];\r\n"
"		  byId('hl7').style.display='block';\r\n"
"		  break; \r\n"
"		case 11:\r\n"
"		  byId('hl8').innerHTML = \"PWD <br> \"+info[i];\r\n"
"		  byId('hl8').style.display='block';\r\n"
"		  break;   \r\n"
"	    case 12:\r\n"
"	       var rssi=info[i];\r\n"
"		   //var myRssi=rssi;\r\n"
"		   if (rssi !='31'){\r\n"
"		   byId('myProgress').style.width='100';\r\n"
"		   rssi=Number(rssi);\r\n"
"		   rssi=130+rssi;\r\n"
"		   console.log('rssi:'+rssi);\r\n"
"		   switch(true){\r\n"
"		     case  (rssi<=20):\r\n"
"			   byId('myBar').style.backgroundColor = 'red';\r\n"
"			   break;\r\n"
"			 case  (rssi<=40):\r\n"
"			   byId('myBar').style.backgroundColor = 'orange';\r\n"
"			   break;			 \r\n"
"		   }\r\n"
"		  \r\n"
"		   byId('myBar').style.width=rssi + \"%\";\r\n"
"		   byId('myBar').innerHTML=rssi+ \"%\";	   \r\n"
"		   }else{\r\n"
"		   byId('myBar').style.width=0;\r\n"
"		   byId('myProgress').style.width=0;\r\n"
"		   }\r\n"
"		   break; \r\n"
"	     		  		   		   \r\n"
"		}\r\n"
"	  }\r\n"
"   }\r\n"
"    \r\n"
"}\r\n"
" \r\n"
" \r\n"
"function request(url){\r\n"
"   //alert(\"Call me!!\");\r\n"
"  var xhr = new XMLHttpRequest(); \r\n"
"  xhr.onreadystatechange=function(event){\r\n"
"   if(xhr.readyState === 4 && xhr.status === 200){\r\n"
"     //alert(\"Call me from Ajax!!\");\r\n"
"	  //console.log(xhr.responseText);\r\n"
"	  //console.log(xhr.responseText.search('scanwifi='));\r\n"
"	  //console.log(xhr.responseText.search('status='));\r\n"
"	   if(xhr.responseText.search('info=')==0){ \r\n"
"	    espInfo(xhr.responseText);\r\n"
"	   }\r\n"
"    } else if(xhr.readyState === 4 && xhr.status===0){\r\n"
"	if(url==='/scanwifi?'){byId('scan').value='Scan Error !';}\r\n"
"	if(url==='/lan_status?'){\r\n"
"	 byId('loader').innerHTML='Load Error!';\r\n"
"	 byId('wanloader').innerHTML='Load Error!';\r\n"
"	 byId('dateloader').innerHTML='Load Error!';\r\n"
"	 loader=true;}\r\n"
"	}\r\n"
"  }\r\n"
"  xhr.open(\"POST\",urladdress+url+Math.random(),true);\r\n"
"  xhr.send();\r\n"
" }\r\n"
"</script>\r\n"
"\r\n"
"\r\n"
"\r\n"
"<table>\r\n"
"<tr>\r\n"
"  <th style='background-color:white;display: block;' > SYSTEM INFO </th>\r\n"
"</tr>\r\n"
"\r\n"
"<!-- line 1 date/time -->\r\n"
"<tr>\r\n"
"  <th id='hl1' >My First Line </th>\r\n"
"   <!--<td> some info </td>-->\r\n"
"</tr>\r\n"
"<!-- line 2 Temperature Mqtt: -->\r\n"
"<tr>\r\n"
"  <th id='hl2'> My Second Line </th>\r\n"
"    <!--<td id='dl2'> some info </td>-->\r\n"
"</tr>\r\n"
"<!-- line 3  Auto Mode -->\r\n"
"<tr>\r\n"
"  <th id='hl3'> My Third ine </th>\r\n"
"</tr>\r\n"
"<!-- line 4  On:10:23  Off:13:34 -->\r\n"
"<tr>\r\n"
"  <th id='hl4'> My Fourth Line </th>\r\n"
"</tr>\r\n"
"<!-- line 5 Status: Manual / Auto/ Sleep -->\r\n"
"<tr>\r\n"
"  <th id='hl5'> My Fifth Line </th>\r\n"
"</tr>\r\n"
"<!-- Line 6 Power: On/Off -->\r\n"
"<tr>\r\n"
"  <th id='hl6'> My Sixth Line </th>\r\n"
"</tr>\r\n"
"<!-- Line 7 IP: -->\r\n"
"<tr>\r\n"
"  <th id='hl7'> My Seventh Line </th>\r\n"
"</tr>\r\n"
"<!-- Line 8 Pwd: -->\r\n"
"<tr>\r\n"
"  <th id='hl8'> My Eighth Line </th>\r\n"
"</tr>\r\n"
"<tr> \r\n"
"<tr>\r\n"
"  <th style='display: block;' id='hl9'> \r\n"
"   Signal \r\n"
"  <!--<progress id='prgRSSI'  label-signal=\"lala\" style='display:none;border-radius:8px;' value=\"0\" min=\"0\" max=\"70\">12</progress>-->\r\n"
"  <div id=\"myProgress\">\r\n"
"    <div id=\"myBar\"></div>\r\n"
"  </div> 	\r\n"
"  </th>\r\n"
"</tr>\r\n"
"<tr> \r\n"
"  \r\n"
"  <th style='display: block;'>\r\n"
"  <a href='./' >\r\n"
"      SETUP    \r\n"
"   </a>\r\n"
"  </th> \r\n"
" \r\n"
"</tr>\r\n"
"\r\n"
"</table>\r\n"
"<!-- Info page -->\r\n"
"\r\n"
"</body>\r\n"
"</html>\r\n"