"<!doctype html>\r\n"
"<html>\r\n"
"<meta http-equiv=\"Cache-Control\" content=\"no-cache\" />\r\n"
"<meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n"
"<script>\r\n"
"\r\n"
"//document.addEventListener(\"DOMContentLoaded\", function()\r\n"
"\r\n"
"window.onload=function(){\r\n"
"var select=byId('lan_select');\r\n"
"//readStatus();\r\n"
"\r\n"
"//alert('I am Here !');\r\n"
"//byClass('lantype').value=select.options[0].text;\r\n"
"select.selectedIndex=0;\r\n"
"select.addEventListener('change',function(){\r\n"
" changeSelect();\r\n"
"});\r\n"
"\r\n"
"byId('lan_setup').addEventListener('click',function(){\r\n"
" console.log('Click header lan'); \r\n"
"  if(lanshow)lanShow();\r\n"
"  else lanHide();\r\n"
"});\r\n"
"\r\n"
"byId('wan_setup').addEventListener('click',function(){\r\n"
"  console.log('Click header wan');\r\n"
"   if(wanshow) wanShow();\r\n"
"   else  wanHide();     \r\n"
"});\r\n"
"\r\n"
"\r\n"
"\r\n"
"byId('date_setup').addEventListener('click',function(){\r\n"
"  if(dateshow)dateShow(); \r\n"
"  else dateHide();  \r\n"
"});\r\n"
"\r\n"
"byId('mqtt_setup').addEventListener('click',function(){\r\n"
"  if(mqttshow)mqttShow(); \r\n"
"  else mqttHide();  \r\n"
"});\r\n"
"\r\n"
"byId('update_setup').addEventListener('click',function(){\r\n"
" if(updateshow) updateShow();\r\n"
"  else updateHide();\r\n"
"});\r\n"
"\r\n"
"byId('loader').addEventListener('click',function(){if(loader){readStatus()};});\r\n"
"byId('wanloader').addEventListener('click',function(){if(loader){readStatus()};});\r\n"
"}\r\n"
"\r\n"
"\r\n"
"function byId(id){return document.getElementById(id)};\r\n"
"function byClass(id){return document.getElementsByClassName(id)[0]};\r\n"
"function byClassi(id,i){return document.getElementsByClassName(id)[i]};\r\n"
"function byTag(id){return document.getElementsByTagName(id)[0]};\r\n"
"var lanshow=true;\r\n"
"var wanshow=true;\r\n"
"var loader=false;\r\n"
"var dateshow=true;\r\n"
"var mqttshow=true;\r\n"
"var updateshow=true;\r\n"
"var boot='unknow';\r\n"
"var version='unknow';\r\n"
"var sum=0x0000;\r\n"
"//var urladdress='http://127.0.0.1:3000';\r\n"
"//var urladdress='http://10.10.10.1';\r\n"
"//var urladdress='http://192.168.88.254';\r\n"
"var urladdress=window.location;\r\n"
"console.log(urladdress);\r\n"
"function dateShow(){\r\n"
"   readDate()\r\n"
"   byId('date_form').style.display='block';\r\n"
"   byId('date_setup').style.backgroundColor='rgba(25, 255, 7, 0.32)'; \r\n"
"   dateshow=false\r\n"
"   lanHide();\r\n"
"   wanHide();   \r\n"
"   showSystemDate(); \r\n"
"   showSystemTime();  \r\n"
"   var showTime=setInterval(showSystemTime,1000);\r\n"
"}\r\n"
"function dateHide(){\r\n"
"  byId('date_form').style.display='none';\r\n"
"  byId('date_setup').style.backgroundColor='rgba(128, 128, 128, 0.48)';\r\n"
"  dateshow=true;\r\n"
"  //clearInterval(showTime);\r\n"
"}\r\n"
"function showSystemTime(){\r\n"
"  var now=new Date();\r\n"
"  var hour = now.getHours();\r\n"
"   if (hour<10) hour='0'+hour; \r\n"
"  var minute = now.getMinutes();\r\n"
"   if (minute<10) minute='0'+minute; \r\n"
"  var second = now.getSeconds();\r\n"
"  if (second<10) second='0'+second; \r\n"
"  byId('systemTime').innerHTML=hour+':'+minute+':'+second;\r\n"
"  //showSystemDate();\r\n"
"}\r\n"
"function showSystemDate(){\r\n"
"  var now=new Date();\r\n"
"  var year=now.getFullYear();\r\n"
"  var month=now.getMonth()+1;\r\n"
"  if (month<10) month='0'+month;\r\n"
"  var date=now.getDate();\r\n"
"  if (date<10) date='0'+date;\r\n"
"  //console.log(now);\r\n"
"  //console.log(date+\"/\"+month+\"/\"+year);\r\n"
"  byId('systemDate').innerHTML=date+\"/\"+month+\"/\"+year; \r\n"
"}\r\n"
"function lanShow(){\r\n"
"  readStatus();\r\n"
"  byId('lan_form').style.display='block';\r\n"
"  byId('lan_setup').style.backgroundColor='rgba(25, 255, 7, 0.32)';\r\n"
"  lanshow=false;\r\n"
"  wanHide();\r\n"
"  dateHide();\r\n"
"}\r\n"
"function lanHide(){\r\n"
"  byId('lan_form').style.display='none';\r\n"
"  byId('lan_setup').style.backgroundColor='rgba(128, 128, 128, 0.48)';\r\n"
"  lanshow=true;\r\n"
"}\r\n"
"function wanShow(){\r\n"
"  readStatus();\r\n"
"  byId('wan_form').style.display='block';\r\n"
"  byId('wan_setup').style.backgroundColor='rgba(25, 255, 7, 0.32)'; \r\n"
"  wanshow=false;  \r\n"
"  lanHide();\r\n"
"  dateHide();\r\n"
"  \r\n"
"}\r\n"
"function wanHide(){\r\n"
"  byId('wan_form').style.display='none';\r\n"
"  byId('wan_setup').style.backgroundColor='rgba(128, 128, 128, 0.48)';\r\n"
"  wanshow=true;  \r\n"
"}\r\n"
"function mqttShow(){\r\n"
" readMqttServer();\r\n"
" byId('mqtt_form').style.display='block';\r\n"
" byId('mqtt_setup').style.backgroundColor='rgba(25, 255, 7, 0.32)';\r\n"
" mqttshow=false; \r\n"
" }\r\n"
"function mqttHide(){\r\n"
"  byId('mqtt_form').style.display='none';\r\n"
"  byId('mqtt_setup').style.backgroundColor='rgba(128, 128, 128, 0.48)';\r\n"
"  mqttshow=true;  \r\n"
" }\r\n"
"function updateShow(){\r\n"
"  console.log('Update Show');\r\n"
"  boot='unknow';\r\n"
"  version='unknow';\r\n"
"  //byId('update_form').style.display='block';\r\n"
"  byId('lbl_boot').style.display='block'; \r\n"
"  byId('update_setup').style.backgroundColor='rgba(25, 255, 7, 0.32)';\r\n"
"  byId('update_form').style.display='none';\r\n"
"  byId('lbl_boot').innerHTML='BOOT ROM:'+boot;\r\n"
"  updateshow=false;  \r\n"
"  byId('progress').value=0;\r\n"
"  request('/boot?');\r\n"
" }\r\n"
"function updateHide(){\r\n"
" byId('update_form').style.display='none';\r\n"
" byId('update_setup').style.backgroundColor='rgba(128, 128, 128, 0.48)';\r\n"
" byId('lbl_boot').style.display='none';\r\n"
" byId('uploaded').innerHTML='';\r\n"
" byId('progress').style.display='none';\r\n"
" updateshow=true; \r\n"
" \r\n"
" }\r\n"
"function readStatus(){\r\n"
" console.log('read status');\r\n"
" byId('loader').innerHTML='Loading...';\r\n"
" byId('wanloader').innerHTML='Loading...';\r\n"
" byClass('lanssid').value='';\r\n"
" byClass('lanpwd').value='';\r\n"
" byId('wan_select').value='';\r\n"
"  //select.selectedIndex=0;\r\n"
" byClass('wanpwd').value='';\r\n"
" loader=false;\r\n"
"request('/lan_status?');}\r\n"
"function readDate(){\r\n"
" byId('deviceDate').innerHTML=\"\";\r\n"
" byId('deviceTime').innerHTML=\"\";\r\n"
" byId('dateloader').innerHTML='Loading ...';\r\n"
" loader=false;\r\n"
" request('/date?');\r\n"
"}\r\n"
"\r\n"
"function readMqttServer(){\r\n"
" byId('mqttHost').value=\"\";\r\n"
"  byId('mqttPort').value=\"\";\r\n"
"  byId('mqttUser').value=\"\";\r\n"
"  byId('mqttPwd').value=\"\";\r\n"
"  byId('mqttrTopic').value=\"\";\r\n"
"  byId('mqttwTopic').value=\"\"; \r\n"
" request('/mqttServer?');\r\n"
"\r\n"
"}\r\n"
"\r\n"
"function deviceDate(data){\r\n"
"  byId('dateloader').innerHTML='Load OK';\r\n"
"  var data=data.split('&');\r\n"
"   //console.log(data);\r\n"
"   var y=data[1];\r\n"
"   y=\"20\"+y;\r\n"
"   var m=data[2];\r\n"
"   if(m<10)m='0'+m;\r\n"
"   var d=data[3];\r\n"
"   if(d<10) d='0'+d;\r\n"
"   var h=data[4]; \r\n"
"   if(h<10)h='0'+h;\r\n"
"   var min=data[5];\r\n"
"   if(min<10) min='0'+min;\r\n"
"   var sec=data[6];\r\n"
"   if(sec<10) sec='0'+sec;  \r\n"
"   byId('deviceDate').innerHTML=d+'/'+m+'/'+y;\r\n"
"   byId('deviceTime').innerHTML=h+':'+min+ ':'+ sec;  \r\n"
"}\r\n"
"function changeSelect(){\r\n"
" var value=byId('lan_select').value;\r\n"
" console.log(value);\r\n"
" //byClass('lantype').value=byId('lan_select').options[value].text;\r\n"
"}\r\n"
"\r\n"
"function readBootVersion(data){\r\n"
"    console.log(data);\r\n"
"   var data=data.split('&');\r\n"
"     boot=data[1];\r\n"
"	 version=data[3];\r\n"
"	 byId('update_form').style.display='block';\r\n"
"	 byId('lbl_boot').innerHTML='BOOT ROM:'+boot;\r\n"
"	 if (boot==='0'){\r\n"
"	 byId('lbl_update').innerHTML='File to Update: user2.1024.new.2.bin';\r\n"
"	 } else{\r\n"
"	 byId('lbl_update').innerHTML='File to Update: user1.1024.new.2.bin';\r\n"
"	 }\r\n"
"	 //updateShow();\r\n"
" }\r\n"
"\r\n"
"function espData(data){\r\n"
"  console.log(data);\r\n"
"    loader=true;\r\n"
"    byId('loader').innerHTML='Load done!';\r\n"
"	byId('wanloader').innerHTML='Load done!';\r\n"
"   var data = data.split('&');  \r\n"
"     //console.log(data.length);   \r\n"
"    for(i=1;i<data.length;i++){\r\n"
"	   switch(i){\r\n"
"	     case 1:\r\n"
"		  byClass('lanssid').value=data[i];\r\n"
"		  //alert(data[i]);\r\n"
"		  break;\r\n"
"		 case 2:\r\n"
"		  byClass('lanpwd').value=data[i];\r\n"
"		  //alert(data[i]);\r\n"
"		  break;\r\n"
"		 case 3:	\r\n"
"		  var value=data[i];\r\n"
"		   if(value<6 && value>0)\r\n"
"		   {\r\n"
"		    //byClass('lantype').value=byId('lan_select').options[value].text;\r\n"
"			byId('lan_select').value=value;\r\n"
"		    //byClass('lantype').value=byId('sec').options(value).value;  \r\n"
"		   }\r\n"
"		   else\r\n"
"		   {\r\n"
"		      //byClass('lantype').value='OPEN';\r\n"
"		   }		  \r\n"
"         break;		\r\n"
"		 case 4:\r\n"
"		   var value=data[i];\r\n"
"		    if ( value !=null){\r\n"
"			 if(value ==='1'){\r\n"
"		    byId('chkBoxLan').checked=true;  \r\n"
"		   }else{\r\n"
"		    byId('chkBoxLan').checked=false;  \r\n"
"		   }\r\n"
"			\r\n"
"			}\r\n"
"         case 5:\r\n"
"           var value=data[i];\r\n"
"		      //console.log(value);\r\n"
"             if (value !=null){\r\n"
"			 byId('wan_select').options.length=0;\r\n"
"			 var option=document.createElement('option');\r\n"
"			 option.text=value;\r\n"
"	         byId('wan_select').add(option);\r\n"
"			 byId('scan').value='Scan';\r\n"
"			}\r\n"
"		 break;\r\n"
"         case 6:\r\n"
"		   var value=data[i];\r\n"
"		      console.log(value);\r\n"
"             if (value !=null){byClass('wanpwd').value=value;}\r\n"
"	     break;	\r\n"
"         case 7:\r\n"
"		   var value=data[i];\r\n"
"		    if ( value !=null){\r\n"
"			 if(value ==='1'){\r\n"
"		    byId('chkBoxWan').checked=true;  \r\n"
"		   }else{\r\n"
"		    byId('chkBoxWan').checked=false;  \r\n"
"		   }\r\n"
"			\r\n"
"			}		 \r\n"
"	     case 8:\r\n"
"		   var value= data[i];\r\n"
"		   console.log(value);\r\n"
"		   if(value ==='1')\r\n"
"		   {\r\n"
"		    var value='SSID is Connected ! IP:'+data[i+1];\r\n"
"		    byId('wanssid').innerHTML=value;		    \r\n"
"		   }\r\n"
"		    else {byId('wanssid').innerHTML='SSID'};\r\n"
"		 break;	 \r\n"
"		 case 10:\r\n"
"		   var rssi=data[i];\r\n"
"		   console.log('rssi:'+rssi);\r\n"
"		   if (rssi !='31'){\r\n"
"		   rssi=Number(rssi);\r\n"
"		   rssi=100+rssi;\r\n"
"		   console.log('rssi:'+rssi);\r\n"
"		   if(rssi<=15){\r\n"
"		   byId('prgRSSI').style.color='red';\r\n"
"		   } else {\r\n"
"		     byId('prgRSSI').style.color='green';\r\n"
"		   }\r\n"
"		    \r\n"
"		   byId('prgRSSI').value=rssi;\r\n"
"		   byId('prgRSSI').style.display='inline';\r\n"
"		   }else{\r\n"
"		     byId('prgRSSI').style.display='none';\r\n"
"		   }console.log('rssi:'+rssi);\r\n"
"		   break;\r\n"
"	   }    	\r\n"
"     }\r\n"
" }\r\n"
" \r\n"
"function saveMqttServer(){\r\n"
"  console.log('Push Save mqtt server button');\r\n"
"  //byId('mqttHost').value\r\n"
"  request('/mqttServerSave?');\r\n"
"  return false;\r\n"
"}\r\n"
"\r\n"
"function reset_esp(){\r\n"
"  console.log('Push Reset button');\r\n"
"  request('/esp8266Reset?');\r\n"
"  return false;\r\n"
"}\r\n"
"\r\n"
"function testMqttServer(){\r\n"
"  console.log('Push Test mqtt server button');\r\n"
"  \r\n"
"  var send='/mqttServer='+'&'+byId('mqttHost').value +'&'+byId('mqttPort').value +'&'+byId('mqttUser').value+'&'+byId('mqttPwd').value+'&'+byId('mqttrTopic').value+'&'+byId('mqttwTopic').value+'&';\r\n"
"  byId('mqttHost').value=\"\";\r\n"
"  byId('mqttPort').value=\"\";\r\n"
"  byId('mqttUser').value=\"\";\r\n"
"  byId('mqttPwd').value=\"\";\r\n"
"  byId('mqttrTopic').value=\"\";\r\n"
"  byId('mqttwTopic').value=\"\";   \r\n"
"  //console.log(send);\r\n"
"  request(send);\r\n"
"  return false;\r\n"
"}\r\n"
" \r\n"
" function respondMqttServer(data){\r\n"
"     var data = data.split(\"&\");\r\n"
"     //console.log(data);  \r\n"
"       // console.log	((data[1].split(\"host=\")).slice(1)); \r\n"
"	   //console.log('Number:'+byClass('inpmqttsrv').length);\r\n"
"	   \r\n"
"	   if((data[0].split(\"mqttserver=\")).slice(1)==1){\r\n"
"       var i=0;\r\n"
"	   while(byClassi('inpmqttsrv',i)!=undefined){\r\n"
"	     byClassi('inpmqttsrv',i).style.backgroundColor='rgba(25, 255, 7, 0.32)';\r\n"
"		 i++;\r\n"
"	   }		   \r\n"
"	   }else{\r\n"
"	    var i=0;\r\n"
"	    while(byClassi('inpmqttsrv',i)!=undefined){\r\n"
"	     byClassi('inpmqttsrv',i).style.backgroundColor='Crimson';\r\n"
"		 i++;\r\n"
"	      }		   	    \r\n"
"	     }\r\n"
"	   \r\n"
"       byId('mqttHost').value=(data[1].split(\"host=\")).slice(1);\r\n"
"	    byId('mqttPort').value=(data[2].split(\"port=\")).slice(1);\r\n"
"		 byId('mqttUser').value=(data[3].split(\"user=\")).slice(1);\r\n"
"		  byId('mqttPwd').value=(data[4].split(\"pwd=\")).slice(1);\r\n"
"		   byId('mqttrTopic').value=(data[5].split(\"rtopic=\")).slice(1);\r\n"
"		    byId('mqttwTopic').value=(data[6].split(\"wtopic=\")).slice(1);\r\n"
"			\r\n"
"	\r\n"
" }\r\n"
" \r\n"
"function request(url){\r\n"
"   //alert(\"Call me!!\");\r\n"
"  var xhr = new XMLHttpRequest(); \r\n"
"  xhr.onreadystatechange=function(event){\r\n"
"   if(xhr.readyState === 4 && xhr.status === 200){\r\n"
"     //alert(\"Call me from Ajax!!\");\r\n"
"	  //console.log(xhr.responseText);\r\n"
"	  //console.log(xhr.responseText.search('scanwifi='));\r\n"
"	  //console.log(xhr.responseText.search('status='));\r\n"
"	   if(xhr.responseText.search('status=')==0){ \r\n"
"	    espData(xhr.responseText);\r\n"
"	   }\r\n"
"	    else if(xhr.responseText.search('scanwifi=')==0){\r\n"
"	     scanWifiResult(xhr.responseText);\r\n"
"	   }\r\n"
"	   else if(xhr.responseText.search('date=')==0){\r\n"
"	     deviceDate(xhr.responseText);\r\n"
"	   }\r\n"
"	   else if(xhr.responseText.search('boot=')==0){\r\n"
"	     readBootVersion(xhr.responseText);\r\n"
"	   } else if(xhr.responseText.search('mqttserver')==0){\r\n"
"	      respondMqttServer(xhr.responseText);\r\n"
"	      //console.log(xhr.responseText);\r\n"
"	   } else if(xhr.responseText.search('Mqtt Server')==0) {\r\n"
"	      alert(xhr.responseText);\r\n"
"		  readMqttServer();\r\n"
"	   }  else if(xhr.responseText.search('ESP rebooted')==0) {\r\n"
"	      alert(xhr.responseText);\r\n"
"		  //readMqttServer();\r\n"
"	   }\r\n"
"	   \r\n"
"    } else if(xhr.readyState === 4 && xhr.status===0){\r\n"
"	if(url==='/scanwifi?'){byId('scan').value='Scan Error !';}\r\n"
"	if(url==='/lan_status?'){\r\n"
"	 byId('loader').innerHTML='Load Error!';\r\n"
"	 byId('wanloader').innerHTML='Load Error!';\r\n"
"	 byId('dateloader').innerHTML='Load Error!';\r\n"
"	 loader=true;}\r\n"
"	}\r\n"
"  }\r\n"
"  xhr.open(\"POST\",urladdress+url+\"=\"+Math.random(),true);\r\n"
"  xhr.send();\r\n"
"}\r\n"
"function LanSub(){\r\n"
" console.log('Lan submit');\r\n"
" //console.log(select.value);\r\n"
" var chk=0;\r\n"
" if(byId('chkBoxLan').checked===true)chk=1;\r\n"
" var send='/lanform='+'&'+byClass('lanssid').value +'&'+byClass('lanpwd').value +'&'+byId('lan_select').value+'&'+chk;\r\n"
" console.log(send);\r\n"
" request(send);\r\n"
" return false;\r\n"
"}\r\n"
"function WanSub(){\r\n"
" console.log('Wan submit');\r\n"
" //console.log(select.value);\r\n"
" var chk=0;\r\n"
" if(byId('chkBoxWan').checked===true)chk=1;\r\n"
" var send='/wanform='+'&'+byId('wan_select').value +'&'+byClass('wanpwd').value+'&'+chk;\r\n"
" console.log(send);\r\n"
" request(send);\r\n"
" return false;\r\n"
"}\r\n"
"function UpdateSub(s){\r\n"
"console.log('Update Submit');\r\n"
"\r\n"
"//console.log(s);\r\n"
"var f= byId('fileUpdate').files[0];\r\n"
"//console.log(f);\r\n"
"if (f===undefined || f===null){\r\n"
"  alert(\"No file Select\");\r\n"
"  return false;\r\n"
"}\r\n"
"if(boot==0){\r\n"
"  if(f.name!='user2.1024.new.2.bin'){\r\n"
"    alert('Wrong bin file');\r\n"
"	return false;\r\n"
"  }\r\n"
"}\r\n"
"\r\n"
"if(boot==1){\r\n"
" if(f.name!='user1.1024.new.2.bin'){\r\n"
"    alert('Wrong bin file');\r\n"
"	return false;\r\n"
"  }\r\n"
"}\r\n"
"\r\n"
"\r\n"
" if(sum===0 || sum==undefined) {\r\n"
"  alert('Check Sum Error'+sum);\r\n"
" return;\r\n"
" }\r\n"
" \r\n"
"var xhr = new XMLHttpRequest();\r\n"
"xhr.open('POST',urladdress+'/update/name='+f.name+'/size='+f.size+'/sum='+sum,true);\r\n"
"//xhr.open('POST',urladdress+'/update/name='+f.name+'/size='+f.size,true);\r\n"
"\r\n"
" xhr.upload.onprogress= function(e){\r\n"
"  var progress=(e.loaded/e.total)*100;\r\n"
"   //console.log('Progress:'+progress);\r\n"
"    byId('progress').value=progress;\r\n"
"   //console.log('Progress:'+e.total);  \r\n"
" }\r\n"
" \r\n"
" xhr.onloadstart =function(e){\r\n"
"   console.log('Start');\r\n"
"   byId('progress').style.display='inline';\r\n"
"    byId('progress').value=5;  \r\n"
" }\r\n"
" \r\n"
" xhr.onloadend = function(e){\r\n"
"   console.log('End');\r\n"
"   byId('uploaded').innerHTML='File upload done!';\r\n"
" } \r\n"
" \r\n"
"xhr.onload =function(oEvent){\r\n"
"    if(xhr.readyState === 4 && xhr.status === 200){\r\n"
"	\r\n"
"	console.log('File Uploaded:'+xhr.responseText);\r\n"
"	//console.log('LRC:'+xhr.responseText.search('done.LRC:OK'));\r\n"
"     if(xhr.responseText.search('Wrong')==0){\r\n"
"	   //byId('progress').value=0;\r\n"
"	   byId('progress').style.display='none';\r\n"
"	   //alert(xhr.responseText);\r\n"
"	 }else if(xhr.responseText.search('done.LRC:OK')==14){\r\n"
"	    //File succesufull uploaded if corect Check Sum Change Boot and Reboot....\r\n"
"		 console.log('File uploded done!');\r\n"
"		 //confirm('Change boot ROM ?');		 \r\n"
"	      if(confirm('Change boot ROM ?')==true){\r\n"
"		      console.log('Change boot ROM !!!');\r\n"
"			  ChangeBoot();\r\n"
"		    } else {\r\n"
"		         alert('No Change Boot');		    \r\n"
"		      }		 	 \r\n"
"	 }else {alert(xhr.responseText);}\r\n"
"	 \r\n"
"	}\r\n"
"  };\r\n"
" xhr.send(f);\r\n"
" return false;\r\n"
"}\r\n"
"function ChangeBoot(){\r\n"
"  console.log('Call changeboot.....');\r\n"
" request('/changeBoot?');\r\n"
"}\r\n"
"function CheckSum(){\r\n"
" var f= byId('fileUpdate').files[0];\r\n"
" if (f===undefined || f===null){\r\n"
"  return false;\r\n"
"  }\r\n"
"  var fr = new FileReader();\r\n"
"  var ready=false;\r\n"
"   sum =  0x00;  \r\n"
" fr.onload =  function(e) {\r\n"
"    var rawData=new Int8Array(e.target.result);\r\n"
"	console.log(rawData.length);\r\n"
"	if(rawData.length>450000){\r\n"
"	 alert('File is too big');\r\n"
"	 byId('update').style.display='none';\r\n"
"	}else byId('update').style.display='inline';\r\n"
"    for(i=0;i<rawData.length;i++){\r\n"
"    sum=(sum^rawData[i])&0xff;	\r\n"
"	}\r\n"
"	//if(sum<0){sum=Math.abs(sum) +128};\r\n"
"	//console.log('Check Sum:'+sum);\r\n"
"	return sum;\r\n"
"	//return sum=sum.toString(16);\r\n"
" };\r\n"
"  fr.readAsArrayBuffer(f);\r\n"
"}\r\n"
"function MqqtSub(e){\r\n"
"console.log('Push Send me mqtt....');\r\n"
"console.log(e);\r\n"
"console.log(e.originalEvent.explicitOriginalTarget);\r\n"
"console.log(e.target.id);\r\n"
"return false;\r\n"
"}\r\n"
"function DateSub(){\r\n"
"  console.log('Date submit');\r\n"
"  var now=new Date();\r\n"
"  var hour = now.getHours();\r\n"
"  var minute = now.getMinutes();\r\n"
"  var second = now.getSeconds();\r\n"
"  var year=now.getFullYear();\r\n"
"  year=year-2000;\r\n"
"  var month=now.getMonth()+1;\r\n"
"  var date=now.getDate();\r\n"
"  var day=now.getDay();\r\n"
"  var send='&'+year+'&'+month+'&'+date+'&'+hour+'&'+minute+'&'+second+'&'+day+'&\\n';\r\n"
"  request('/date='+send);\r\n"
"  return false;\r\n"
"}\r\n"
"function scanWifi(){\r\n"
" console.log('Scan Wifi');\r\n"
" byId('wanssid').innerHTML='SSID'\r\n"
" byClass('wanpwd').value=null;\r\n"
" byId('scan').value='Scanning...';\r\n"
" request('/scanwifi?');\r\n"
"}\r\n"
"function scanWifiResult(data){\r\n"
"  //Create wan_select options base in data\r\n"
"     //console.log(data);\r\n"
"	byId('scan').value='Scan done!';	\r\n"
"	var  wan_select=byId('wan_select');\r\n"
"	wan_select.options.length=0;\r\n"
"    var data = data.split('&');\r\n"
"	 for(i=1;i<data.length;i++){\r\n"
"	   //console.log(data[i]); \r\n"
"       var option=document.createElement('option');	   \r\n"
"	   option.text=data[i];\r\n"
"	   wan_select.add(option);\r\n"
"	 }\r\n"
"}\r\n"
"function openFile(e){\r\n"
" console.log('OpenFile:'+e);\r\n"
" \r\n"
"}\r\n"
"</script>\r\n"
"\r\n"
"<style>\r\n"
"\r\n"
"table {width:15%;\r\n"
"        margin-left:auto;\r\n"
"        margin-right:auto;\r\n"
"}\r\n"
"th,td {display: inline-block;\r\n"
"       border-radius: 8px;\r\n"
"  \r\n"
"}\r\n"
"\r\n"
"th {background-color: rgba(128, 128, 128, 0.48);margin:5px;width: 300px;height:38px;font-size:30px;}\r\n"
"td {text-align:center;display:none;}\r\n"
"a {text-decoration:none;color:black;display:block;width:100%;}\r\n"
"body{text-align:center;}\r\n"
"label{display:block;text-align:center;}\r\n"
"input,select {border-radius:8px;outline:none;}\r\n"
"select{border-width:2px;;-webkit-appearance: none;-moz-appearance: none;appearance:none;width:172px;height:20px;border-style:solid;,input}\r\n"
"select::-ms-expand { display: none;}  \r\n"
"/*input.lantype:hover #lan_select{visibility:visible;}*/\r\n"
"form {display:inline-block; text-align:center;}\r\n"
"/*form#lan_form,#wan_form,#date_form,#mqtt_form,#update_form{display:none;}*/\r\n"
"#send{margin:7px;}\r\n"
"#scan{margin:5px 0 3px;}\r\n"
"label#loader,#wanloader{cursor:pointer;}\r\n"
".inpmqttsrv{background-color:rgba(128, 128, 128, 0.48)};\r\n"
"\r\n"
"</style>\r\n"
"\r\n"
"<title> ESP8266 LAN</title>\r\n"
"\r\n"
"<body>\r\n"
"\r\n"
"<table>\r\n"
"<tr>\r\n"
"  <th style='background-color:white;' >SETUP</th>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"  <th id='lan_setup'> LAN </th>\r\n"
"   <td id='lan_form' >\r\n"
"     <form autocomplete='off' onSubmit='return LanSub()'>\r\n"
"     <label>SSID</label>\r\n"
"     <input type='text' class='lanssid' list='list_ssid' name='ssid' required>\r\n"
"     <label>PASSWORD </label> \r\n"
"     <input class='lanpwd' type='password' name='pwd' pattern='^.{8,}$' title='Password can not be shorter that 8 chars.Also,cant contains only numbers' required >\r\n"
"     <br>\r\n"
"     <labeL>TYPE</label>\r\n"
"     <label>\r\n"
"     <select id='lan_select'>\r\n"
"     <option value='0'>OPEN</option>\r\n"
"	 <option value='1'>WEP</option>\r\n"
"	 <option value='2'>WPA_PSK</option>\r\n"
"	 <option value='3'>WPA2_PSK</option>\r\n"
"	 <option value='4'>WPA_WPA2_PSK</option>\r\n"
"	 <option value='5'>MAX</option> \r\n"
"     </select>\r\n"
"     </label>\r\n"
"     \r\n"
"	 <br>\r\n"
"	 <label>ON/OFF</label>\r\n"
"     <input id='chkBoxLan' type='checkbox'>\r\n"
"	 <br>\r\n"
"	 <!--\r\n"
"      <input class='lantype' name='security' pattern='(^OPEN|WEP|WPA_PSK|WPA_WPA2_PSK|AUTH_WPA_WPA2_PSK|MAX)' title='OPEN,WEP,WPA_PSK,WPA_WPA2_PSK,AUTH_WPA_WPA2_PSK,MAX' required >-->\r\n"
"     <input id='send'  type=\"submit\" value='Save'>\r\n"
"      <label id='loader'></label>\r\n"
"     </form>\r\n"
"  </td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"  <th id='wan_setup'> WAN </th>\r\n"
"    <td id='wan_form'>\r\n"
"	  <form   autocomplete='off' onSubmit='return WanSub()'>\r\n"
"		  <label id='wanssid'>SSID</label> \r\n"
"		  <label>\r\n"
"		  <select id='wan_select'> \r\n"
"		  </select>\r\n"
"		  </label>\r\n"
"		  <input id='scan' type='button' value='Scan' onclick='scanWifi()'>\r\n"
"		  <!--<input  class='wan_ssid' name='wan_ssid'   required>-->\r\n"
"		  <label>PASSWORD</label>\r\n"
"		  <input type='password' class='wanpwd' required >\r\n"
"		  <br>\r\n"
"		  <label>ON/OFF</label>\r\n"
"		   <input id='chkBoxWan' type='checkbox'>\r\n"
"		   <br>\r\n"
"		  <input id='send' type=\"submit\" value='Save'>\r\n"
"		  <label id='wanloader'></label>\r\n"
"		  <progress id='prgRSSI' style='display:none' value=\"0\" min=\"0\" max=\"70\"></progress>\r\n"
"	  </form>\r\n"
"  </td>\r\n"
"    <!--<td> some info </td>-->\r\n"
"</tr>\r\n"
"<tr>\r\n"
"  <th>\r\n"
"   <a style='text-decoration: none;color:black;' href=\"./program.html\">\r\n"
"    PROGRAM\r\n"
"   </a>  \r\n"
"  </th>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"  <th>\r\n"
"   <a style='text-decoration: none;color:black;' href=\"./info.html\">\r\n"
"    INFO\r\n"
"   </a>  \r\n"
"  </th>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"  <th id='date_setup'>DATE</th>\r\n"
"   <td id='date_form'>\r\n"
"    <form  autocomplete='off' onSubmit='return DateSub()' >\r\n"
"	<label> Device Date </label>\r\n"
"	<label id='deviceDate'></label>\r\n"
"	<label id='deviceTime'></label>\r\n"
"	<label> System Date </label>\r\n"
"	<label id='systemDate'></label>\r\n"
"	<label id=\"systemTime\"></label> \r\n"
"	<input id='send' type=\"submit\" value='Save'>\r\n"
"	<label id='dateloader'></label>\r\n"
"	</form>\r\n"
"   </td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"  <th id='mqtt_setup'>MQTT SERVER</th>\r\n"
"   <td id='mqtt_form'>\r\n"
"   	<form autocomplete='off'  >  <!-- onSubmit='return MqqtSub(event)'-->\r\n"
"	<label>  MQTT SERVER HOST </label>\r\n"
"	<input class='inpmqttsrv' id='mqttHost' type='text' >\r\n"
"	<label> MQTT SERVER PORT </label>\r\n"
"	<input class='inpmqttsrv' id='mqttPort' type='text' >\r\n"
"	<label> MQTT USER </label>\r\n"
"	<input class='inpmqttsrv' id='mqttUser' type='text' >\r\n"
"	<label> MQTT PASSWORD </label>\r\n"
"	<input class='inpmqttsrv' id='mqttPwd' type='text' >\r\n"
"	<label>MQTT READ TOPIC </label>\r\n"
"	<input class='inpmqttsrv' id='mqttrTopic' type='text' >\r\n"
"	<label>MQTT WRITE TOPIC</label>\r\n"
"	<input class='inpmqttsrv' id='mqttwTopic' type='text' >\r\n"
"	<br>\r\n"
"	<input type='submit' value='Test' id='send' onclick='return testMqttServer()' >\r\n"
"	<br>\r\n"
"	<input type='submit' value='Save' id='send'  onclick='return saveMqttServer()' >\r\n"
"	<br>\r\n"
"	<input type='submit' value='Reset' id='send'  onclick='return reset_esp()' >\r\n"
"	</form>\r\n"
"   </td>\r\n"
"</tr>\r\n"
"<tr>\r\n"
"  <th id='update_setup' >OTA UPDATE</th>\r\n"
"   <td id='update_form'>\r\n"
"	<label  id='lbl_boot' > </label>\r\n"
"	<form autocomplete='off' onSubmit='return UpdateSub()' >\r\n"
"	<label id='lbl_update'> File to Update </label>\r\n"
"	<input type='file'  id='fileUpdate' NAME=\"fileName\" SIZE=\"35\" MAXLENGTH=\"255\" accept='.bin'  onchange='CheckSum()' >\r\n"
"	<br>\r\n"
"	<input type='submit' value='Update' id='update' >\r\n"
"	</form>\r\n"
"	<progress id='progress' style='display:none' value='0' max='100'></progress>\r\n"
"	<label id='uploaded'></label>\r\n"
"   </td>\r\n"
"</tr>\r\n"
"<!--<tr> \r\n"
"   <th>\r\n"
"    <a href=\"./\" >\r\n"
"      BACK    \r\n"
"    </a>\r\n"
"  </th> \r\n"
"</tr>\r\n"
"-->\r\n"
"</table>\r\n"
"</body>\r\n"
"</html>\r\n"